### ISSUE TITLE
Numbers limited to approximately 15 digits

### ISSUE THREAD

**Issue by alanhett** [alanhett/ace#2]
Use library such at https://github.com/peterolson/BigInteger.js to handle bigger ints

**Comment by alanhett** [comment]
Resolved. Now handles ints of any size.

**Comment by BenWiederhake** [comment]
Fun fact: We just had a real-life race condition.  I opened the file twice for some reason, and was very, *very* confused that the `encode` and `decode` functions worked differently (`x` in front vs. `x` at end.)

**Comment by BenWiederhake** [comment]
Question:  If you don't care too much about space efficiency, why use different encodings at all?  Numbers could be printed with full accuracy to a string, and there already is a way to encode a string.  If you're feeling fancy, you could even go for whole objects being encoded (via json; I suggest a `z` prefix.)

**Comment by alanhett** [comment]
It's just an aesthetic thing. It really has no practical application other
than to use that special set of letters.

**Comment by BenWiederhake** [comment]
Sure, but [fiddling around](https://github.com/BenWiederhake/minprn) with [pointless things](https://github.com/BenWiederhake/ohno) can still be [fun](https://github.com/BenWiederhake/95voices). :)

**Comment by alanhett** [comment]
Ints over 15 digits now treated as strings
